---
- name: Test_changepass
  hosts: all
  become: true
  vars:
    myuser: "root"
    mypassword: "1"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
